### ISSUE TITLE
Telescope workflow implementation: OAPEN Access Stats by IRUS-UK

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#244]
Details to be updated.

See https://docs.google.com/document/d/14y7lRHYr3MxGzTsiP3j60t7DOJ1tsJLLAMMhQeDHNMA for more info

**Comment by aroelo** [comment]
@alkimozaygen @rhosking 
Requirements based on the OA data trust doc and discussion with Alkim:

- Updated monthly using API
- Processed in the Oapen Google Cloud project, store results in table there
- Results can be appended, so create 1 table in BigQuery that stays up to date, plus 1 table with individual partitions. 
- IP addresses are not included in the table, instead used to look up location info (city, lat., long., country, country code)
- Expected schema, please have a look at the question marks for descriptions/modes:
```yaml
[
  {
    "description": "Item identifier, OAPEN ID assigned to each title.",
    "mode": "REQUIRED",
    "name": "item_id",
    "type": "STRING"
  },
  {
    "description": "Title of the book.",
    "mode": "REQUIRED",
    "name": "book_title",
    "type": "STRING"
  },
  {
    "description": "Begin date.",
    "mode": "REQUIRED",
    "name": "begin_date",
    "type": "DATE"
  },
  {
    "description": "End date.",
    "mode": "REQUIRED",
    "name": "end_date",
    "type": "DATE"
  },
  {
    "description": "?",
    "mode": "REQUIRED",
    "name": "total_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "?",
    "mode": "REQUIRED",
    "name": "total_item_requests",
    "type": "INTEGER"
  },
  {
    "description": "?",
    "mode": "REQUIRED",
    "name": "unique_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "?",
    "mode": "REQUIRED",
    "name": "unique_item_requests",
    "type": "INTEGER"
  },
  {
    "description": "The country name associated with the client.",
    "mode": "?",
    "name": "country",
    "type": "STRING"
  },
  {
    "description": "The country code associated with the client.",
    "mode": "?",
    "name": "country_code",
    "type": "STRING"
  },
  {
    "description": "Latitude based on the client's IP address.",
    "mode": "?",
    "name": "ip_lat",
    "type": "FLOAT"
  },
  {
    "description": "Longitude based on the client's IP address .",
    "mode": "?",
    "name": "ip_lon",
    "type": "FLOAT"
  },
  {
    "description": "City based on the client's IP address.",
    "mode": "?",
    "name": "ip_city",
    "type": "STRING"
  },
  {
    "description": "Country based on the client's IP address",
    "mode": "?",
    "name": "ip_country",
    "type": "STRING"
  },
  {
    "description": "Country code based on the client's IP address",
    "mode": "?",
    "name": "ip_country_code",
    "type": "STRING"
  }
]
```
- Use the GeoLite2 MaxMind database for IP address look up. 
There are a couple of ways of doing this and the easiest solution I believe is to download the database locally and use the python geoip2 API to look up ip address info.
Alternatively, there is a public dataset available in BigQuery from geolite2. However, the ipv4 address is in CIDR format, meaning that we would have to first convert this to a start/end range of IP addresses to look up a single IP address of interest. Also, we would have to first upload data in BigQuery and then run an additional query to translate the IP address in location info.

Using the geolite database locally gives the advantage that the location info can be looked up directly after getting the access stats data from the oapen API, before uploading anything to BigQuery. It does require signing up with MaxMind/geolite to create a user ID and license key. The databases are available in different formats, one of which is their 'mmdb' format that is compatible to use with their API. It is ~70 mb in size.

There is also a webservice available, but usage is limited to 1000 calls per day.

Questions / To Do
- What would be the most fitting name for the telescope/table: oapen_access_stats, oapen_irus_uk, something else?
- Do we wish to store the data in a bucket inside the OAPEN project, like with the other telescopes?
- I noticed that not all IP addresses can be found inside the geolite database. As an example, for 1 month of data (2020-04) out of 193.612 clients, 648 had a private IP address or one that could not be found in the database. Also, for 13.671 clients there was no 'country' info available that is returned directly from the oapen API. What should the values be for these fields, just an empty field?
- How to schedule & execute the telescope/script/dag:
    Since this is run in the OAPEN project, there are some questions regarding how to schedule this, some options:
    - Set-up cloud composer in the project, there are some costs associated with keeping this running while it only has to execute a relatively small task once per month
    - Create a compute engine, run continuously and start telescope with e.g. a cron job.
    - Create a compute engine, start and stop manually once per month. Run telescope manually, it will check for the last time the BigQuery table was updated and pull/upload data accordingly.
    - Create an academic-observatory instance in the OAPEN project, like with cloud composer this will have costs associated keeping it running.
    - Do we create a separate telescope to pull/copy the table from the OAPEN project to our own project?
    - Adapt our current academic-observatory so it can run airflow from our own project, but run tasks/dags inside another project. This might be the most elegant, but will require quite some time to develop I suspect.

For now I have developed code that will pull the access stats data using the API, downloads the geolite database and translates IP address to location info. To continue any further I think it would be best to first address the questions above.
