### ISSUE TITLE
Merge schema's of new and old OAPEN IRUS UK access stats platform

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#424]
The schema's for the new platform (using the API) and old platform (using their website) are quite similar.
As suggested by @jdddog, perhaps it would be easier to work with 1 schema instead.

Currently, the older v1 schema:
<details>

```yaml
[
  {
    "description": "Proprietary ID for the book.",
    "mode": "NULLABLE",
    "name": "proprietary_id",
    "type": "STRING"
  },
  {
    "description": "Title of the book",
    "mode": "NULLABLE",
    "name": "book_title",
    "type": "STRING"
  },
  {
    "description": "",
    "mode": "NULLABLE",
    "name": "grant",
    "type": "STRING"
  },
  {
    "description": "",
    "mode": "NULLABLE",
    "name": "grant_number",
    "type": "STRING"
  },
  {
    "description": "The book's DOI.",
    "mode": "NULLABLE",
    "name": "doi",
    "type": "STRING"
  },
  {
    "description": "The book's ISBN.",
    "mode": "NULLABLE",
    "name": "isbn",
    "type": "STRING"
  },
  {
    "description": "The latitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lat",
    "type": "FLOAT"
  },
  {
    "description": "The longitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lon",
    "type": "FLOAT"
  },
  {
    "description": "The city based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_city",
    "type": "STRING"
  },
  {
    "description": "The country based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country",
    "type": "STRING"
  },
  {
    "description": "The country code based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country_code",
    "type": "STRING"
  },
  {
    "description": "The publisher",
    "mode": "NULLABLE",
    "name": "publisher",
    "type": "STRING"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "begin_date",
    "type": "DATE"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "end_date",
    "type": "DATE"
  },
  {
    "description": "The total number of title requests.",
    "mode": "NULLABLE",
    "name": "title_requests",
    "type": "INTEGER"
  },
  {
    "mode": "REQUIRED",
    "name": "release_date",
    "type": "DATE",
    "description": "Last day of the release month. Table is partitioned on this column."
  }
]
```
</details>

The newer v2 schema:
<details>

```yaml
[
  {
    "description": "Proprietary identifier of the book.",
    "mode": "NULLABLE",
    "name": "proprietary_id",
    "type": "STRING"
  },
  {
    "description": "URI of the book.",
    "mode": "NULLABLE",
    "name": "URI",
    "type": "STRING"
  },
  {
    "description": "DOI of the book.",
    "mode": "NULLABLE",
    "name": "DOI",
    "type": "STRING"
  },
  {
    "description": "ISBN of the book.",
    "mode": "NULLABLE",
    "name": "ISBN",
    "type": "STRING"
  },
  {
    "description": "Title of the book",
    "mode": "NULLABLE",
    "name": "book_title",
    "type": "STRING"
  },
  {
    "description": "The country of the client registered by oapen irus uk.",
    "mode": "NULLABLE",
    "name": "country",
    "type": "STRING"
  },
  {
    "description": "The country code of the client registered by oapen irus uk.",
    "mode": "NULLABLE",
    "name": "country_code",
    "type": "STRING"
  },
  {
    "description": "The latitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lat",
    "type": "FLOAT"
  },
  {
    "description": "The longitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lon",
    "type": "FLOAT"
  },
  {
    "description": "The city based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_city",
    "type": "STRING"
  },
  {
    "description": "The country based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country",
    "type": "STRING"
  },
  {
    "description": "The country code based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country_code",
    "type": "STRING"
  },
  {
    "description": "The publisher",
    "mode": "NULLABLE",
    "name": "publisher",
    "type": "STRING"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "begin_date",
    "type": "DATE"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "end_date",
    "type": "DATE"
  },
  {
    "description": "The total number of item investigations.",
    "mode": "NULLABLE",
    "name": "total_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "The total number of item requests.",
    "mode": "NULLABLE",
    "name": "total_item_requests",
    "type": "INTEGER"
  },
  {
    "description": "The number of unique item investigations",
    "mode": "NULLABLE",
    "name": "unique_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "The number of unique item requests",
    "mode": "NULLABLE",
    "name": "unique_item_requests",
    "type": "INTEGER"
  },
  {
    "mode": "REQUIRED",
    "name": "release_date",
    "type": "DATE",
    "description": "Last day of the release month. Table is partitioned on this column."
  }
]
```
</details>

Mapping v1 fields (left) to v2 fields (right)
- proprietary_id <-> proprietary_id
- book_title <-> book_title
- _NA_ <-> URI
- grant <-> _NA_
- grant_number <-> _NA_
- doi <-> DOI
- isbn <-> ISBN
- _NA_ <-> country
- _NA_ <-> country_code
- client_lat <-> client_lat
- client_lon <-> client_lon
- client_city <-> client_city
- client_country <-> client_country
- client_country_code <-> client_country_code
- publisher <-> publisher
- begin-date <-> begin_date
- end_date <-> end_date
- title_requests <-> total_item_requests ??
- _NA_ <-> total_item_investigations
- _NA_ <-> unique_item_investigations
- _NA_ <-> unique_item_requests
- release_date <-> release_date

Proposed merged schema:

```yaml
[
  {
    "description": "Proprietary identifier of the book.",
    "mode": "NULLABLE",
    "name": "proprietary_id",
    "type": "STRING"
  },
  {
    "description": "URI of the book. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "URI",
    "type": "STRING"
  },
  {
    "description": "DOI of the book.",
    "mode": "NULLABLE",
    "name": "DOI",
    "type": "STRING"
  },
  {
    "description": "ISBN of the book.",
    "mode": "NULLABLE",
    "name": "ISBN",
    "type": "STRING"
  },
  {
    "description": "Title of the book",
    "mode": "NULLABLE",
    "name": "book_title",
    "type": "STRING"
  },
  {
    "description": "Grant. Only available for data before 2020-04-01.",
    "mode": "NULLABLE",
    "name": "grant",
    "type": "STRING"
  },
  {
    "description": "Grant number. Only available for data before 2020-04-01.",
    "mode": "NULLABLE",
    "name": "grant_number",
    "type": "STRING"
  },
  {
    "description": "The country of the client registered by oapen irus uk. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "country",
    "type": "STRING"
  },
  {
    "description": "The country code of the client registered by oapen irus uk. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "country_code",
    "type": "STRING"
  },
  {
    "description": "The latitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lat",
    "type": "FLOAT"
  },
  {
    "description": "The longitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lon",
    "type": "FLOAT"
  },
  {
    "description": "The city based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_city",
    "type": "STRING"
  },
  {
    "description": "The country based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country",
    "type": "STRING"
  },
  {
    "description": "The country code based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country_code",
    "type": "STRING"
  },
  {
    "description": "The publisher",
    "mode": "NULLABLE",
    "name": "publisher",
    "type": "STRING"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "begin_date",
    "type": "DATE"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "end_date",
    "type": "DATE"
  },
  {
    "description": "The total number of item investigations. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "total_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "The total number of item requests. ??? Same as old 'title_requests' ??? ",
    "mode": "NULLABLE",
    "name": "total_item_requests",
    "type": "INTEGER"
  },
  {
    "description": "The number of unique item investigations. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "unique_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "The number of unique item requests. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "unique_item_requests",
    "type": "INTEGER"
  },
  {
    "mode": "REQUIRED",
    "name": "release_date",
    "type": "DATE",
    "description": "Last day of the release month. Table is partitioned on this column."
  }
]
```

@alkimozaygen @rhosking Could you have a look at this to see if that seems right? @alkimozaygen Do you know if the `title_requests` is the same as the `total_item_requests`? Or perhaps we should add both of those as unique fields in the merged schema?

**Comment by rhosking** [comment]
@aroelo for country and country_code can I just confirm, is that something that they are providing directly, or is that computed via the geo_ip lookup?

Just looking at the requirements documentation. Is this the Platform or Item report API? and what is the difference. I also noticed that you can choose optional attributes, do we have a list of which ones we are asking for?

**Comment by alkimozaygen** [comment]
@aroelo title_request in Counter 4 is not the same as unique_item_request or total_item_request in Counter 5.
In Counter 5 the ‘Total_Item_Requests’: the total number of times the full text of a content item was downloaded or viewed.

I asked Ronald from OAPEN and he said that he would like to get Total_item_request instead of Unique_title_request.

**Comment by aroelo** [comment]
> @aroelo for country and country_code can I just confirm, is that something that they are providing directly, or is that computed via the geo_ip lookup?

The `country` and `country_code` are provided by oapen irus uk for the data before 2020-04. For both the new and old platforms the `client_country` and `client_country_code` are added as well, these are computed from the geo_ip lookup.

> Just looking at the requirements documentation. Is this the Platform or Item report API? and what is the difference. I also noticed that you can choose optional attributes, do we have a list of which ones we are asking for?

I'm not sure. We're using the following path: `https://irus.jisc.ac.uk/sushiservice/oapen/reports/oapen_ir/`. Based on the 'oapen_ir' I would say this is an Item Report.

I can't find the `oapen_ir` back in the documentation here: https://irus.jisc.ac.uk/r5/uk/embed/api/ though.
@alkimozaygen is it the same as `irus_ir`, do you know the differences?

This is the parameter that is used to show attributes: `&attributes_to_show=Client_IP%7CCountry`
From the data trust google doc it says this about the attributes_to_show:
> Optional Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values). Multiple attribute names are delimited with a | character. Options include Country and Client_IP. When fields are included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.

**Comment by aroelo** [comment]
> @aroelo title_request in Counter 4 is not the same as unique_item_request or total_item_request in Counter 5.
> In Counter 5 the ‘Total_Item_Requests’: the total number of times the full text of a content item was downloaded or viewed.
> 
> I asked Ronald from OAPEN and he said that he would like to get Total_item_request instead of Unique_title_request.

Which one would Ronald like to get? Is this for Counter 5 you mean? The `total_item_request` is already available there, would he like to add `unique_title_request` as well you mean?

If that is the case then I think it would make sense to have them as separate fields in the merged schema. It would then look like:

Mapping v1 fields (left) to v2 fields (right)
- proprietary_id <-> proprietary_id
- book_title <-> book_title
- _NA_ <-> URI
- grant <-> _NA_
- grant_number <-> _NA_
- doi <-> DOI
- isbn <-> ISBN
- _NA_ <-> country
- _NA_ <-> country_code
- client_lat <-> client_lat
- client_lon <-> client_lon
- client_city <-> client_city
- client_country <-> client_country
- client_country_code <-> client_country_code
- publisher <-> publisher
- begin-date <-> begin_date
- end_date <-> end_date
- title_requests <-> _NA_
- _NA_ <-> total_item_requests
- _NA_ <-> total_item_investigations
- _NA_ <-> unique_item_investigations
- _NA_ <-> unique_item_requests
- release_date <-> release_date


Proposed merged schema:

```yaml
[
  {
    "description": "Proprietary identifier of the book.",
    "mode": "NULLABLE",
    "name": "proprietary_id",
    "type": "STRING"
  },
  {
    "description": "URI of the book. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "URI",
    "type": "STRING"
  },
  {
    "description": "DOI of the book.",
    "mode": "NULLABLE",
    "name": "DOI",
    "type": "STRING"
  },
  {
    "description": "ISBN of the book.",
    "mode": "NULLABLE",
    "name": "ISBN",
    "type": "STRING"
  },
  {
    "description": "Title of the book",
    "mode": "NULLABLE",
    "name": "book_title",
    "type": "STRING"
  },
  {
    "description": "Grant. Only available for data before 2020-04-01.",
    "mode": "NULLABLE",
    "name": "grant",
    "type": "STRING"
  },
  {
    "description": "Grant number. Only available for data before 2020-04-01.",
    "mode": "NULLABLE",
    "name": "grant_number",
    "type": "STRING"
  },
  {
    "description": "The country of the client registered by oapen irus uk. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "country",
    "type": "STRING"
  },
  {
    "description": "The country code of the client registered by oapen irus uk. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "country_code",
    "type": "STRING"
  },
  {
    "description": "The latitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lat",
    "type": "FLOAT"
  },
  {
    "description": "The longitude based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_lon",
    "type": "FLOAT"
  },
  {
    "description": "The city based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_city",
    "type": "STRING"
  },
  {
    "description": "The country based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country",
    "type": "STRING"
  },
  {
    "description": "The country code based on the client's ip address.",
    "mode": "NULLABLE",
    "name": "client_country_code",
    "type": "STRING"
  },
  {
    "description": "The publisher",
    "mode": "NULLABLE",
    "name": "publisher",
    "type": "STRING"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "begin_date",
    "type": "DATE"
  },
  {
    "description": "The begin date of the investigated period.",
    "mode": "NULLABLE",
    "name": "end_date",
    "type": "DATE"
  },
  {
    "description": "The total number of title requests. Only available for data before 2020-04-01.",
    "mode": "NULLABLE",
    "name": "title_requests",
    "type": "INTEGER"
  },
  {
    "description": "The total number of item investigations. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "total_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "The total number of item requests. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "total_item_requests",
    "type": "INTEGER"
  },
  {
    "description": "The number of unique item investigations. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "unique_item_investigations",
    "type": "INTEGER"
  },
  {
    "description": "The number of unique item requests. Only available for data since 2020-04-01.",
    "mode": "NULLABLE",
    "name": "unique_item_requests",
    "type": "INTEGER"
  },
  {
    "mode": "REQUIRED",
    "name": "release_date",
    "type": "DATE",
    "description": "Last day of the release month. Table is partitioned on this column."
  }
]
```
