### ISSUE TITLE
Increase Celery visibility timeout

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#446]
When an Airflow task is running in our production server (using Celery workers) it will timeout after 6 hours.
The messages in the log will then look something like this:
```
[2021-07-13 20:40:17,622] {taskinstance.py:664} INFO - Dependencies not met for <TaskInstance: orcid.download_transferred 2021-07-04T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-07-13 20:40:17,624] {local_task_job.py:90} INFO - Task is not able to be run
```

It seems like the task will still continue to run, but this is a problem, because there is no logging available. So if a task fails it is unclear why it failed or other important logging might be missed.

I believe this issue is caused by the Celery visibility_timeout setting, the value can be set in the airflow config file (see [here](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#visibility-timeout)) and the Airflow default value is None, but is set to 21600 (seconds = 6 hours) as default by Celery. The visibility_timeout is described as:
>The visibility timeout defines the number of seconds to wait for the worker to acknowledge the task before the message is redelivered to another worker. Make sure to increase the visibility timeout to match the time of the longest ETA you’re planning to use. visibility_timeout is only supported for Redis and SQS celery brokers. See: http://docs.celeryproject.org/en/master/userguide/configuration.html#std:setting-broker_transport_options

It is also mentioned in the airflow documentation here: https://airflow.apache.org/docs/apache-airflow/stable/executor/celery.html?highlight=visibility#celery-executor

Under 'Some caveats' it mentions:
> Make sure to set a visibility timeout in [celery_broker_transport_options] that exceeds the ETA of your longest running task

So what I think happens is that a Celery worker will pick up an Airflow task, runs it for 6 hours, and then another worker is scheduled to run this same task (hence the log message that dependencies are not met, this must come from the second worker?). It seems like the first worker will keep running and finish the job though, because when this is the case the task state will eventually be set to 'SUCCESS', not sure how this part and the communication with Redis works in regards to the timeout.

Anyway, I think we should increase the visibility time out, I'm not sure about the right limit though. I know there are some very long tasks (especially the sensors, maybe we can disregard those). The downside for setting the value too high is that if a worker crashes just before it will run a task, it will take as long as the visibility_timeout for this task to be run with another worker (as I understand from the comment here: https://stackoverflow.com/a/41303598)

For ORCID I tried setting it to 24 hours and this worked, I've simply added the following line to the `docker-compose.observatory.yml.jinja2` file:

```yaml
{# Local settings -#}
x-environment: &environment
  # Airflow settings
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgres://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_hostname }}:5432/{{ airflow_db_name }}"
  AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
  AIRFLOW__CORE__AIRFLOW_HOME: /opt/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
  AIRFLOW__CELERY__BROKER_URL: "redis://:@{{ redis_hostname }}:6379/0"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_hostname }}:5432/{{ airflow_db_name }}"
  {%- if config.backend.type.value == 'terraform' %}
  AIRFLOW__CORE__REMOTE_LOGGING: "True"
  AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "gs://${AIRFLOW_VAR_AIRFLOW_BUCKET}/logs"
  AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "google_cloud_observatory"
  AIRFLOW__SECRETS__BACKEND: "airflow.contrib.secrets.gcp_secrets_manager.CloudSecretsManagerBackend"
  AIRFLOW__SECRETS__BACKEND_KWARGS: "{'connections_prefix': 'airflow-connections', 'variables_prefix': 'airflow-variables', 'sep': '-'}"
  AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__VISIBILITY_TIMEOUT: 86400 <-------- 
  {%- endif %}
```
